#!/bin/bash

max_brightness=$(cat /sys/class/backlight/intel_backlight/max_brightness)
brightness=$(cat /sys/class/backlight/intel_backlight/brightness)

if (($brightness < $max_brightness)); then
  let brightness=$brightness+20
  echo "echo $brightness > /sys/class/backlight/intel_backlight/brightness" | sudo zsh #or bash
fi

# insert in sudoers-file via visudoers
#your_user your_machine = NOPASSWD: /home/mrwu/.config/i3/brightness_up
#your_user your_machine = NOPASSWD: /home/mrwu/.config/i3/brightness_down



